name: Deploy to Environments

on:
  push:
    branches:
      - 'dev/*'        # Dev branches
      - 'staging/*'    # Staging branches
    tags:
      - 'v2024.*'      # Tags for production deployment

  workflow_dispatch:
    inputs:
      version_branch:
        description: 'Version branch to deploy'
        required: true
      environment:
        description: 'Target environment'
        required: true
        default: 'dev'

jobs:
  deploy:
    name: Deploy to Environment
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}  # Check out the branch or tag

      # Automatically set environment based on branch name or tag
      - name: Set Environment Based on Branch
        id: set_envs
        run: |
          if [[ "${{ github.ref }}" == refs/heads/dev/* ]]; then
            ENVIRONMENT="dev"
          elif [[ "${{ github.ref }}" == refs/heads/staging/* ]]; then
            ENVIRONMENT="stg"
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            ENVIRONMENT="prod"
          else
            echo "Invalid environment for deployment. Exiting."
            exit 1
          fi
          echo "::set-output name=environment::$ENVIRONMENT"
          echo "::set-output name=version_branch::${{ github.ref_name }}"

      # Deploy based on environment (automatically mapped based on branch name or tag)
      - name: Deploy to ${{ steps.set_envs.outputs.environment }} environment
        run: |
          echo "Deploying ${{ steps.set_envs.outputs.version_branch }} to ${{ steps.set_envs.outputs.environment }} environment"

  manual-deploy:
    name: Manual Deploy to Environment
    runs-on: ubuntu-latest

    # This job only runs when manually triggered using workflow_dispatch
    if: github.event_name == 'workflow_dispatch'

    steps:
      # Checkout the repository based on the manually provided branch
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.version_branch }}  # Check out the manually provided branch

      # Manually set environment based on input
      - name: Deploy to ${{ inputs.environment }} environment
        run: |
          echo "Deploying ${{ inputs.version_branch }} to ${{ inputs.environment }} environment"

  conditional-deploy:
    name: Conditional Deployment Based on Environment
    runs-on: ubuntu-latest
    needs: deploy

    # Only deploy if specific conditions are met (e.g., specific branches or tags for specific environments)
    steps:
      - name: Deploy to Production (only for tags)
        if: ${{ steps.set_envs.outputs.environment == 'prod' && github.ref_type == 'tag' }}
        run: |
          echo "Deploying tag to production"

      - name: Deploy to Staging (only for staging branches)
        if: ${{ steps.set_envs.outputs.environment == 'stg' && github.ref_type == 'branch' }}
        run: |
          echo "Deploying to staging"

      - name: Deploy to Development (only for dev branches)
        if: ${{ steps.set_envs.outputs.environment == 'dev' && github.ref_type == 'branch' }}
        run: |
          echo "Deploying to development"
